application:
  host: "127.0.0.1"
  port: 3000
  log_level: "Info"
  log_format: "Compact"
  ttl: 1
  rate_limit: 100
  aws_settings:
    region: "eu-central-1"
    bucket_name: "neon-fileshare"
    s3_enabled: true
database:
  username: "neondb_owner"
  host: "ep-young-cell-agc57ajt-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
  password: "npg_6lOnJpeNYHt0"
  name: "fileshare"
  port: 5432



